---
- name: /Rock/3-kubernetes.yml -> Kubernetes master deployment

  hosts: master
  remote_user: pi
  become: true

  roles:
  - role: kubernetes
    mode: master

- name: /Rock/2-kubernetes.yml -> Kubernetes nodes deployment

  hosts: nodes
  remote_user: pi
  become: true

  roles:
  - role: kubernetes
    mode: node
