- name: /Rokc/roles/kubernetes/tasks/kubeadm.yml -> Reset if requested
  command: kubeadm reset
  when: reset
  tags:
    - reset

- name: /Rokc/roles/kubernetes/tasks/kubeadm.yml -> Check for a running cluster
  command: kubectl get nodes
  become_user: pi
  register: kubectl_result
  failed_when: kubectl_result.rc == 2
  changed_when: kubectl_result.rc == 1

- block:

  - name: /Rokc/roles/kubernetes/tasks/kubeadm.yml -> Setup master
    include_tasks: master.yml
    when: mode == "master"

  - name: /Rokc/roles/kubernetes/tasks/kubeadm.yml -> Setup node
    include_tasks: node.yml
    when: mode == "node"

  when: kubectl_result.rc == 1 or reset
