- name: /Rokc/roles/openshift/tasks/install_binaries.yml -> Install Binaries
  copy: src=bin/{{ item }} dest=/usr/bin/{{ item }} owner=root group=root mode=0755
  with_items: "{{ binaries.commands }}"
