- name: /Rokc/roles/base/kubernetes/tasks/cni/weave.yml -> Create Weave resource file
  template: src=cni/weave.yml dest=/etc/kubernetes/kube-weave.yml

- name: /Rokc/roles/base/kubernetes/tasks/cni/weave.yml -> Create Weave resources
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  command: kubectl create -f /etc/kubernetes/kube-weave.yml
