- name: /Rokc/roles/base/tasks/apt.yml -> Add apt-transport-https
  apt:
    name: 'apt-transport-https'
    state: present
    force: yes

- name: /Rokc/roles/base/tasks/apt.yml -> Add Kubernetes Repo Key
  apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: /Rokc/roles/base/tasks/apt.yml -> Add Docker Repo Key
  apt_key: 
    id: F76221572C52609D
    keyserver: hkp://keyserver.ubuntu.com:80

- name: /Rokc/roles/base/tasks/apt.yml -> Add Kubernetes Repo
  # Try to pick up latest stable builds. Switch over to '-unstable' if targeting latest releases
  apt_repository: repo='deb http://apt.kubernetes.io/ kubernetes-xenial main' state=present

- name: /Rokc/roles/base/tasks/apt.yml -> Add Docker Repo
  apt_repository: repo='deb [arch=armhf] https://apt.dockerproject.org/repo raspbian-jessie main' state=present
  
- name: /Rokc/roles/base/tasks/apt.yml -> Update APT package cache and upgrade
  apt:
    update_cache: yes
    autoremove: yes
    upgrade: yes

- name: /Rokc/roles/base/tasks/apt.yml -> Install Packages
  apt:
    pkg:
      - hdparm
      - iperf
      - mtr-tiny
      - bridge-utils
      - socat
      - jq
      - vim
      - dnsutils
    force: yes
    state: present